# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-10-17 17:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BugManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bugName', models.CharField(max_length=128, verbose_name='bug\u540d\u79f0')),
                ('bugDetail', models.CharField(max_length=256, verbose_name='bug\u8be6\u60c5')),
                ('bugStatus', models.CharField(choices=[('\u6fc0\u6d3b', '\u6fc0\u6d3b'), ('\u5df2\u89e3\u51b3', '\u5df2\u89e3\u51b3'), ('\u5173\u95ed', '\u5173\u95ed')], default='\u6fc0\u6d3b', max_length=32, null=True, verbose_name='bug\u72b6\u6001')),
                ('bugLevel', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], default='3', max_length=32, null=True, verbose_name='bug\u7b49\u7ea7')),
                ('bugCreate', models.CharField(max_length=32, verbose_name='bug\u521b\u5efa\u8005')),
                ('bugAssign', models.CharField(max_length=32, verbose_name='bug\u5206\u914d\u7ed9')),
                ('bugCreateTime', models.DateTimeField(auto_now=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('Product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
            ],
            options={
                'verbose_name': 'Bug\u7ba1\u7406',
                'verbose_name_plural': 'Bug\u7ba1\u7406',
            },
        ),
    ]
