# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-10-14 02:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('apitest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apiName', models.CharField(max_length=128, verbose_name='\u63a5\u53e3\u540d\u79f0')),
                ('apiUrl', models.CharField(max_length=128, verbose_name='\u63a5\u53e3\u5730\u5740')),
                ('apiParamValue', models.CharField(max_length=128, verbose_name='\u53c2\u6570\u548c\u503c')),
                ('apiMethod', models.CharField(choices=[('0', 'get'), ('1', 'post'), ('2', 'put'), ('3', 'delete'), ('4', 'patch')], default='0', max_length=256, null=True, verbose_name='\u8bf7\u6c42\u65b9\u6cd5')),
                ('apiResult', models.CharField(max_length=256, verbose_name='\u9884\u671f\u7ed3\u679c')),
                ('apiStatus', models.BooleanField(verbose_name='\u662f\u5426\u901a\u8fc7')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
            ],
            options={
                'verbose_name': '\u5355\u4e00\u573a\u666f\u63a5\u53e3\u6d4b\u8bd5',
                'verbose_name_plural': '\u5355\u4e00\u573a\u666f\u63a5\u53e3\u6d4b\u8bd5',
            },
        ),
    ]
